### ISSUE TITLE
allow DataOne plugins to work with both DataObjects and Collections

### ISSUE THREAD

**Issue by michael-conway** [DFC-Incubator/dfc-dataone#14]
in 

https://github.com/DFC-Incubator/dfc-dataone/blob/master/dataone-node/src/main/java/org/irods/jargon/dataone/tier1/MNReadImpl.java#L153-L215

Refactor to a callout to repo service to allow the archiving of a collection into dissemination object before streaming download.

**Comment by slr71** [comment]
The scope of this issue needs to be expanded somewhat because operations other than streaming a DataOne object are affected by whether the identifier refers to a DataObject or a Collection.

**Comment by michael-conway** [comment]
Dennis not sure when to close this one, if the pull got you there...I'll let you close when you think it's satisfied

**Comment by slr71** [comment]
I think that the pull request solves all of the problems that I was encountering. I was debating whether to put a DataOneObject implementation for collections into this repository, but I think I'll stick with an implementation in the plugin for the time being. We can always create something similar in this repository later.
